### ISSUE TITLE
[BUG] HashBucket Behavior

### ISSUE THREAD

**Issue by albert17** [NVIDIA/NVTabular#402]
**Description**
HashBucket operation uses cudf hashing , which even when hashing integers will be spread out over the complete range of the mod we are using.

**Solution**
Add special case for columns which are integer (int32/int64) so only the mod is performed and not the hashing.

**Comment by alecgunny** [comment]
To make sure I understand, are you saying that if the columns are already integers to not bother hashing them and just mod them instead? I'm not sure why that functionality would be built into the `HashBucket` op if there's just bucketing and no hashing. Seems like this would be better handled by a pretty straightforward `LambdaOp`.

**Comment by albert17** [comment]
I see your point. @benfred probably can discuss this better.

**Comment by benfred** [comment]
> To make sure I understand, are you saying that if the columns are already integers to not bother hashing them and just mod them instead? I'm not sure why that functionality would be built into the HashBucket op if there's just bucketing and no hashing. Seems like this would be better handled by a pretty straightforward LambdaOp.

Yeah - thats the idea here. We're running into some issues were the columns contain small integers, and hashing them with cudf leads to unexpected results - with the byte representation of the integer being hashed. Since the best possible hash function for an integer is the identity function (since its guaranteed collision free) the idea here is to just override the cudf hash_values function for integer columns to be a no-op.

While I agree that you *could* do this pretty easily with a LambdaOp - that argument could be applied for the entire HashBucket  opitself (```LambdaOp(lambda col, gdf: gdf[col].hash_values() % bucket_size)``` ) - and I think this is reasonable behaviour to put in place here.

**Comment by rnyak** [comment]
@benfred does that mean I should also modify my `_hash_bucket` function in categorify op, accordingly?

**Comment by alecgunny** [comment]
> While I agree that you could do this pretty easily with a LambdaOp - that argument could be applied for the entire HashBucket opitself (LambdaOp(lambda col, gdf: gdf[col].hash_values() % bucket_size) ) - and I think this is reasonable behaviour to put in place here.

Couldn't the same be said of any op that doesn't require stats? I think the question is whether we want to support every possible algebraic operation you might want to do on a column as a dedicated op. I implemented the `HashBucket` primarily for transparency to users coming from TF who use the analogous feature column, and since many users may not be familiar with the CuDF `Series.hash_values` method (since its analogy doesn't exist in pandas).

But even if this warrants its own operation, I do wonder if this isn't better addressed as its `Modulo` op. While I agree with your point about hash functions, such an op might be easier to find for users looking for this behavior, rather than requiring them to understand this abstraction beforehand to know to look for that behavior here.

If this is just an extra kwarg you want to tack on to the `HashBucket` op that advanced users with a richer understanding of hash functions can toggle, I suppose that's not the end of the world. But still, I find it odd that users would turn to the `HashBucket` op for applications where they don't want to hash the byte representation of the object in question, and adding this kwarg for that functionality feels like unnecessary complexity.

**Comment by albert17** [comment]
After all the disscusion, we don't want to change the mod op behavior, we want the HugeCTR Notebook to use the operation `LambdaOp(lambda col, gdf: gdf[col].hash_values() % bucket_size)` instead of Mod operation. HugeCTR Notebook will be updated

**Comment by albert17** [comment]
I am appying the operators like this now `proc.add_cat_preprocess([ops.Categorify(dtype = np.int64, out_path=stats_path), ops.LambdaOp(op_name="MOD10M", f=lambda col, gdf: col % 10000000)])`

However when getting the embedding table `print(ops.get_embedding_sizes(proc).values())` I am still seeing values higher than 10M: `dict_values([(220817330, 16), (126535808, 16), (3014529, 16), (400781, 16), (11, 6), (2209, 16), (11869, 16), (148, 16), (4, 3), (977, 16), (15, 7), (38713, 16), (283898298, 16), (39644599, 16), (181767044, 16), (584616, 16), (12883, 16), (109, 16), (37, 12), (17177, 16), (7425, 16), (20266, 16), (4, 3), (7085, 16), (1535, 16), (64, 16)])`

@rnyak Did you see anything similar when wraping HashBucket into Categorify?

@benfred Any idea?

**Comment by rnyak** [comment]
@albert17 this is normal and expected. The Emd table for now can only be generated from `Categorify` op.` LambdaOp` cannot affect embedding table. This is same with `HashBucket` op. With my PR, HashBucket wrapped into Categorify, so you get expected (reduced) embedding size.

**Comment by benfred** [comment]
if you're doing the lambda op to cap the embedding sizes - you'll need to also adjust the output of the get_embedding_size call as well (since it won't be aware of what you're doing )
